# Generated by Django 4.0.5 on 2022-06-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultetlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guruhlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.fakultetlar')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedralar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talabalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.guruhlar')),
            ],
        ),
        migrations.CreateModel(
            name='Ustozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.kafedralar')),
            ],
        ),
        migrations.CreateModel(
            name='Universitetlar_royxati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.fakultetlar')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.fanlar')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.guruhlar')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.kafedralar')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.talabalar')),
                ('ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.ustozlar')),
            ],
        ),
        migrations.AddField(
            model_name='fanlar',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.ustozlar'),
        ),
        migrations.AddField(
            model_name='fakultetlar',
            name='kafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitetlar.kafedralar'),
        ),
    ]
